import type { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import dynamic from "next/dynamic";

import { QueryProvider } from "@/providers/query";
import { ThemeProvider } from "@/providers/theme";
import { AuthProvider } from "@/contexts/auth";
import { JotaiDevTools } from "@/components/jotaiDevTools";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirmatn = localFont({
  src: "../../public/fonts/vazirmatn/Vazirmatn[wght].woff2",
  style: "normal",
  display: "swap",
  variable: "--font-vazirmatn",
});

console.log(vazirmatn);

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={`${vazirmatn.variable} font-vazirmatn antialiased`}>
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <JotaiDevTools />
            <QueryProvider>{children}</QueryProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
